### PR TITLE
#9 added XMS env vars

### PR DESCRIPTION
**Pull request by jhermanski**
As instructed, used restcomm_service.sh from xms branch. Added MS_COMPATIBILITY_MODE and MS_ADDRESS. Preseved Lefty's password change.

### CODE REVIEW

**Comment by leftyb** [comment]
hi @jhermanski,

Please use master branch to create the necessary modifications and then PR. xms branch is very outdated.

Thank you .

**Comment by jhermanski** [comment]
You told me this a while back.

I redid the process, cloning Restcomm-Docker from the master branch. Maybe I messed that up? Then I used restcomm-service.sh from the xms branch, as Henrique instructed me to do some time back. See attached email. I added the two env vars to that.

**Comment by leftyb** [comment]
@jhermanski,

I think that there is a misunderstanding here. You need to use the master branch as it is and apply your modification on the same. So in your case you don't need to use  "restcomm-service.sh" from xms branch but from master branch, and then apply all your modification there. Actually  in this case as "restcomm-service.sh" is changed a lot at the master branch and is not used for configuring the container the proper file to use is [restcomm_conf.sh](https://github.com/RestComm/Restcomm-Docker/blob/master/scripts/restcomm_conf.sh). As you may notice is very similar to "restcomm-service.sh" at the XMS branch you are using, with additional things. File "restcomm_conf.sh" comes from "restcomm-service.st". So safely you can use  "restcomm_conf.sh" to add all the necessary modifications.

Please feel free to contact for any inquires. 

B.R
Lefteris

**Comment by leftyb** [comment]
Done and included  at master branch.

**Comment by jhermanski** [comment]
Hi Lefty,

I looked the 4 scripts I had been working on – I see some familiar things, but maybe not everything?  RECORDING_PATH for example. Is this now completely taken care of?

Thanks.
John

**Comment by leftyb** [comment]
Hi John,

yes RECORDINGS_PATH is been added to the configuration scripts here:

https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/configuration/config-scripts/as7-config-scripts/restcomm/autoconfig.d/config-restcomm.sh#L445

Regards.

On Fri, May 6, 2016 at 6:00 PM, John Hermanski notifications@github.com
wrote:

> Hi Lefty,
> 
> I looked the 4 scripts I had been working on – I see some familiar things,
> but maybe not everything? RECORDING_PATH for example. Is this now
> completely taken care of?
> 
> Thanks.
> John
> 
> From: Lefteris Banos [mailto:notifications@github.com]
> Sent: Thursday, May 05, 2016 8:44 AM
> To: RestComm/Restcomm-Docker
> Cc: John Hermanski; Mention
> Subject: Re: [RestComm/Restcomm-Docker] #9 added XMS env vars (#42)
> 
> Done and included at master branch.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub<
> https://github.com/RestComm/Restcomm-Docker/pull/42#issuecomment-217143265>
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/RestComm/Restcomm-Docker/pull/42#issuecomment-217466392

## 

## 

Lefteris Banos
Restcomm - DevOps
TeleStax Inc.
Email: eleftherios.banos@telestax.com

**Pull request closed without merging**
