### PR TITLE
support JAVA_OPTS_EXTRA

### LINKED ISSUE #53: Add possibility to add custom java options like java agent
add env variable to provide extra value for `JAVA_OPTS`

I propose to use `$JAVA_OPTS_EXTRA`
It will appended before original `$JAVA_OPTS` in `standalone.conf`

**Result:**

```
JAVA_OPTS="$JAVA_OPTS_EXTRA $JAVA_OPTS"
```

### PR DESCRIPTION
**Pull request by hamsterksu**
resolve #53

### CODE REVIEW

**Comment by deruelle** [comment]
@hamsterksu can you rebase to latest master ?
@leftyb will not be able to review before another week

**Comment by hamsterksu** [comment]
@deruelle @leftyb master is rebased

**Comment by deruelle** [comment]
@leftyb can you review this one too ?

**Comment by leftyb** [comment]
I am closing this PR after review, due to modifications are needed.
Comments [here](https://github.com/RestComm/Restcomm-Docker/issues/53)

**Pull request closed without merging**
