### PR TITLE
kubernetes artifects

### PR DESCRIPTION
**Pull request by adimania**
A basic kubernetes replication controller.

### CODE REVIEW

**Comment by leftyb** [comment]
Hi @adimania ,

Thank you for you contribution. Can you please elaborate a bit on the README.md on a  how-to guide  so users can easier  take advantage and use the specific controller you have created.

Thank you.

**Comment by adimania** [comment]
Added elaborate instructions on how to use the controller. 
Thanks.

**Comment by deruelle** [comment]
@leftyb please review

**Comment by leftyb** [comment]
@adimania,

I mistakenly merged your pull request, so I had to revert it due to I need to properly revise and test it and didn't manage to do it yet. I apologise for that. I would like ask you to please when you have the time  create a new pull request so it can be registered that you did this contribution. Again I apologise for the repeated work.

Best Regards

**Pull request merged**
