### PR TITLE
support init password

### PR DESCRIPTION
**Pull request by hamsterksu**

### CODE REVIEW

**Comment by hamsterksu** [comment]
@deruelle i have created new pull request

**Comment by deruelle** [comment]
@leftyb please review and merge

**Comment by leftyb** [comment]
hi @hamsterksu,

I am testing the modification and in a specific case where [HSQL_PERSIST](https://github.com/RestComm/Restcomm-Docker/blob/master/scripts/restcomm_env_locally.sh#L36) is used the modification is not working. 

As you can see [here](https://github.com/leftyb/Restcomm-Docker/blob/init_pswd/scripts/restcomm_conf.sh#L179) the script is copying restcomm.script to the new defined location. Can you please fix that. What you need to do is to include the modification for INIT_PASSWORD before  HSQL_PERSIST at "restcomm_conf.sh" script.

Thank you,
Lefteris.

**Comment by hamsterksu** [comment]
@leftyb done, i suppose we should split this file by sections.

**Comment by leftyb** [comment]
@hamsterksu,

Thank you very much. I will merge your contribution now.
We are in a process of refactoring the docker configuration scripts, so for now, I think that we will leave it like that, until we get the refactoring done.  

B.R.

**Comment by hamsterksu** [comment]
@leftyb thanks, i have one more PR i will push it in 15 min.

**Comment by leftyb** [comment]
@hamsterksu Perfect, thank you!

**Pull request merged**
