### PR TITLE
Add S3_BUCKET_REGION as Docker ENV Closes #67

### LINKED ISSUE #67: Docker environment variable to specify S3_BUCKET_REGION
The bucket region is hard coded to us-west-1 after PR https://github.com/RestComm/Restcomm-Connect/pull/873/files so recordings upload fails when you are uploading to a S3 budget associated to a different region.

Workaround seems modify https://github.com/RestComm/Restcomm-Connect/blob/3d46d612eddc1d4c06f1fd0846cccf4f4e68c257/restcomm/restcomm.application/src/main/webapp/WEB-INF/conf/restcomm.xml to your S3 Bucket region but it would be better to do it using a Docker environment variable.

See https://github.com/RestComm/Restcomm-Connect/issues/871 for more info

### PR DESCRIPTION
**Pull request by antonmry**
See #67 for more info.

PS: by default, it uses us-east-1 as before.

### CODE REVIEW

**Comment by leftyb** [comment]
hi @antonmry,

Thank you for the contribution. You are right it is necessary to add a flag on docker - restcomm side to be able to modify the S3 region.

Will review and comment here.

B.R.

**Comment by leftyb** [comment]
Hi @antonmry,

We have been trying to move all configuration work on RestComm itself using auto-configuration scripts and restcomm.conf. So from Docker we would  need to actually place the proper value of the corresponding configuration at the resctomm.conf [file](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/configuration/config-scripts/as7-config-scripts/restcomm/restcomm.conf). At the moment there is not any configuration of S3 bucket at restcomm.conf file. 
We will need to first add the S3 bucket configuration at restcomm.conf with the appropriate auto-configuration scripts modifications and then from docker side we would need to actually update the value at retcomm.conf. Will you be interested on contributing to add the corresponding S3 modification at the auto-configuration scripts of RestComm? 

Here is what needs to be done: 
1.) Add the necessary configuration from [restcomm.xml](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.application/src/main/webapp/WEB-INF/conf/restcomm.xml#L252) to restcomm.conf. 
2.) Modify [config-restcomm.sh](https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/configuration/config-scripts/as7-config-scripts/restcomm/autoconfig.d/config-restcomm.sh) to apply the values set at restcomm.conf to restcomm.xml

Please feel free to ask if you have any doubts.

**Comment by antonmry** [comment]
Hi @leftyb ,

I'm happy to contribute but there are other contributions on-going, so it may take some time to have the PR ready.

I propose:
1. Accept this PR, so we have the problem solved and all the S3 configuration together.
2. Open an issue to migrate restcomm.xml to restcomm.conf. I will try to work on it as soon as I'm a bit more available.

Does it make sense?

**Comment by leftyb** [comment]
@antonmry,

Ok I agree, I will open the issue for the proper configuration of the S3 bucket.

Thank you.

**Comment by antonmry** [comment]
Thanks @leftyb 

I will subscribe to the issue and let you know as soon as I work on it

**Comment by leftyb** [comment]
@antonmry 
Merged thank you. 

Here the new issue : https://github.com/RestComm/Restcomm-Docker/issues/69

**Pull request merged**
