### PR TITLE
support loadbalancers

### PR DESCRIPTION
**Pull request by hamsterksu**
1. get last version of upstream/master 
2. review changes 

@deruelle FYI
@leftyb FYI

### CODE REVIEW

**Comment by leftyb** [comment]
Hi @hamsterksu,

We have a container build on your branch you can download it and test it from here: restcomm/restcomm:lb. 
I will do the same and update you on that.
Thank you.

**Comment by hamsterksu** [comment]
hi @leftyb,
what about this feature?

**Comment by deruelle** [comment]
@hamsterksu it seems the branch has conflicts, can you rebase againt master so we can merge ?

**Comment by hamsterksu** [comment]
@leftyb @deruelle i have merged master

**Comment by hamsterksu** [comment]
@leftyb thanks, now we can use official docker container :+1: 

Do you rebuild  docker container when build new version of restcomm? i think you can use webhooks for this.

**Comment by leftyb** [comment]
@hamsterksu,

Yes we are updating docker "latest" tag when there are restcomm modifications. 
Please have in mind that the official release tag is "7.5.0".   "latest" tag is considered as beta version.

**Comment by hamsterksu** [comment]
@leftyb do you rebuild 7.5.0 when improve docker repo?

**Comment by leftyb** [comment]
@hamsterksu 
7.5.0 is the latest release [see here](http://telestax.com/telscale-restcomm-7-5-0-ga-released/). Next release is scheduled approximately in two weeks.
So we will not rebuild 7.5.0 container we will create a new one with the latest new release.
As I said earlier you can use "latest" tag but it is a beta version before release.

**Pull request merged**
