### PR TITLE
support init password

### PR DESCRIPTION
**Pull request by hamsterksu**
change admin password for first installation

### CODE REVIEW

**Comment by hamsterksu** [comment]
@leftyb, fixed

**Comment by hamsterksu** [comment]
@leftyb would you like to use plain text for env variable and convert it to md5hash in the script?

**Comment by leftyb** [comment]
@hamsterksu ,

Yes please that is the idea, you can use something like: 
`echo -n "${PASSWD}" | md5sum |cut -f1 -d" "`

But please test it locally if you can before, to make sure that the encryption is the correct one.

Thank you!

**Comment by hamsterksu** [comment]
@leftyb password is plain text now. it will be converted to md5hash automatically

**Comment by leftyb** [comment]
@hamsterksu 
Thank you for your contribution. Looks OK now. I will  give it a test as well and merge it to master.

B.R.

**Comment by hamsterksu** [comment]
@leftyb do you plan to merge this PR? if yes i will resolve conflicts
we need it for current customer

**Comment by deruelle** [comment]
@hamsterksu it seems the branch has conflicts and can't be merged as is. Can you rebase against current master ?

**Pull request closed without merging**
